apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops
  namespace: default
  labels:
    app: hello-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-devops
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      containers:
      - name: hello-devops
        image: 287466334815.dkr.ecr.us-east-1.amazonaws.com/openconnect-id:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
